# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Мордиков Артем Владимирович
- ПИЭ-22-1

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |


знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная
вещь, которая вам никогда не пригодится, но тут вдруг на паре по
математике преподаватель просит всех посчитать число Фибоначчи для
100. Кто-то будет считать вручную (так точно не нужно), кто-то
посчитает на калькуляторе, а кто-то подумает, что он самый крутой и
напишет рекурсивную программу на Python и немного огорчится,
потому что данная программа будет достаточно долго считаться, если
ее просто так запускать. Но именно тут к вам на помощь приходят
декораторы, например @lru_cache (он предназначен для решения задач
динамическим программированием, если простыми словами, то этот
декоратор запоминает промежуточные результаты и при рекурсивном
вызове функции программа не будет считать одни и те же значения, а
просто “возьмёт их из этого декоратора”). Вам нужно написать
программу, которая будет считать числа Фибоначчи для 100 и
запустить ее без этого декоратора и с ним, посмотреть на разницу во
времени решения поставленной задачи.
P.S. при запуске без декоратора можете долго не ждать, для
наглядности хватит 10 секунд ожидания.

```python
from functools import lru_cache  # Импортируем декоратор lru_cache

@lru_cache(None)  # Декоратор для динамического программирования
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == "__main__":
    print(fibonacci(100))
```

### Результат.
![image](https://github.com/user-attachments/assets/854c6acf-3cb6-4bd8-87cf-978fdcd7550b)


## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную
проверку ввода данных пользователя при регистрации. Для этого он
реализовал функцию, которая выводит данные пользователя на экран и
решил, что будет проверять правильность введённых данных при
помощи декоратора, но в этом ему потребовалась ваша помощь.
Напишите декоратор для функции, который будет принимать все
параметры вызываемой функции (имя, возраст) и проверять чтобы
возраст был больше 0 и меньше 130.
Причем заметьте, что неважно сколько пользователь введет данных на
сайт к Илье, будут обрабатываться только первые 2 аргумента

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = "Недопустимый возраст"
        input_func(name, age)

    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

if __name__ == "__main__":
    personal_info("Владимир", 38)
    personal_info("Александр", -5)
    personal_info("Петр", 138, 15, 48, 2)
```

### Результат.
![image](https://github.com/user-attachments/assets/aa837f56-4f95-47b6-acb0-e2d8806ae153)


## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать
вместе с ним. Но вот в вашем проекте появилась проблема, кто-то
пытается сломать вашу функцию с получением данных для сайта. Эта
функция работает только с данными integer, а какой-то недохакер
пытается все сломать и вместо нужного типа данных отправляет string.
Воспользуйтесь исключениями, чтобы неподходящий тип данных не
ломал ваш сайт.
Также дополнительно можете обернуть весь код функции в
try/except/finally для того, чтобы программа вас оповестила о том, что
выявлена какая-то ошибка или программа успешно выполнена

```python
def data(*args):
    try:
        for i in range(len(args[0])):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print("Вся информация обработана")

if __name__ == "__main__":
    data([1, 15, "Hello", "i", "try", "to", "crash", "your", "site", 38, 45])
```

### Результат.
![image](https://github.com/user-attachments/assets/3dd11986-bee7-402b-86b0-47aae64e3828)


## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное
исключение, которое будет вызываться в случае, если в функцию
проверки имени при регистрации передана строка длиннее десяти
символов, а если имя имеет допустимую длину, то в консоль
выводиться “Успешная регистрация”

```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException("Длина более 10 символов")
    else:
        print("Успешная регистрация")

if __name__ == "__main__":
    try:
        name = "12345678910" #второй скрин вместо 12345678910 - name = "12345"
        check_name(name)
    except NegativeValueException as e:
        print(f"Ошибка: {e}")
```

### Результат.
![image](https://github.com/user-attachments/assets/90e80507-72a1-4fff-be3f-228f6e566b91)
![image](https://github.com/user-attachments/assets/a8463c4c-a395-4b84-b1df-e44db63c36c5)


## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер,
для отслеживания его работы. Готовыми вариантами вы не захотели
пользоваться, и поэтому решили создать очень простую пародию. Для
этого создали две функции: __init__() (вызывается при создании класса
декоратора в программе) и __call__() (вызывается при вызове
декоратора). Создайте необходимый вам декоратор. Выведите все логи
в консоль

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')

@SiteChecker
def site():
    print('Усреднённая работа сайта')

if __name__ == "__main__":
    print(">> Сайт запущен")
    site()
    print(">> Сайт выключен")
```

### Результат.
![image](https://github.com/user-attachments/assets/5e152929-2295-46ff-9778-7ee0ec9abc68)

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на Python, но для этого он должен знать, за какое время выполняется его программа. Он решил, что для этого ему идеально подойдёт декоратор для функции, который будет определять, за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time. Декоратор нужно использовать для этой функции: 
Результатом вашей работы будет листинг кода и скриншот консоли, на котором будет выполнена функция Фибоначчи и указано время выполнения программы. Также на этом примере можно увидеть, что решение задач с помощью рекурсии не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но с помощью цикла for ещё и для 200, занимает меньше 1 секунды


```python
import time


def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"\nВремя выполнения: {end_time - start_time:.5f} секунд")
        return result
    return wrapper


@timer_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')


if __name__ == "__main__":
    fibonacci()

```

### Результат.
![image](https://github.com/user-attachments/assets/716cca3a-6f94-445f-9ad5-74f119f9d1a1)

Выводы:
Реализованный декоратор успешно измеряет время выполнения функции, показывая, что программа для вычисления последовательности Фибоначчи выполняется корректно и эффективно. Результаты выводятся на экран, включая последовательность чисел и время выполнения, что подтверждает работоспособность декоратора.

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного
программирования, начав тренировки вы узнали, что для решения
некоторых задач необходимо считывать данные из файлов. Но через
некоторое время вы столкнулись с проблемой что файлы бывают
пустыми, и вы не получаете вводные данные для решения задачи.
После этого вы решили не просто считывать данные из файла, а всю
конструкцию оборачивать в исключения, чтобы избежать такой проблемы. 
Создайте пустой файл и файл, в котором есть какая-то информация. 
Напишите код программы. Если файл пустой, то, нужно
вызвать исключение (“бросить исключение”) и вывести в консоль
“файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file_with_exception_handling(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read().strip()
            if not content:
                raise ValueError("файл пустой")
            print("Содержимое файла:")
            print(content)
    except ValueError as e:
        print(e)
    except FileNotFoundError:
        print("Файл не найден. Убедитесь, что путь указан верно.")
    except Exception as e:
        print(f"Произошла ошибка: {e}")


file_path = "D:\пустой.txt"
read_file_with_exception_handling(file_path)

```

### Результат.
![image](https://github.com/user-attachments/assets/5a7d6c2f-dc14-431f-a3e9-da7897913571)

Выводы:
Программа успешно проверяет содержимое файлов, выбрасывая исключение с сообщением "файл пустой", если файл не содержит данных, и выводя информацию из файла, если он заполнен.

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное
пользователем число, но если пользователь введет строку или другой
неподходящий тип данных, то в консоль выведется ошибка
“Неподходящий тип данных. Ожидалось число.”. Реализовать
функционал программы необходимо через try/except и подобрать
правильный тип исключения. Создавать собственное исключение
нельзя. Проведите несколько тестов, в которых исключение вызывается
и нет. Результатом выполнения задачи будет листинг кода и
получившийся вывод в консоль

```python
def add_two_and_user_input():
    try:
        user_input = input("Введите число: ")
        number = float(user_input) 
        result = 2 + number
        print(f"Результат: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")


add_two_and_user_input()

```

### Результат.
![image](https://github.com/user-attachments/assets/998d52a6-f681-47d7-bb21-876195d8b39b)

Выводы:
Функция успешно складывает число 2 с введённым пользователем числом, корректно обрабатывая ошибки ввода. При введении некорректного типа данных, например строки, выбрасывается исключение ValueError, и выводится сообщение "Неподходящий тип данных. Ожидалось число". Это позволяет избежать сбоев программы и обеспечивает её устойчивость к ошибкам пользователя.

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для
двух любых вами придуманных функций. Декораторы, которые
использовались ранее в работе нельзя воссоздавать. Результатом
выполнения задачи будет: класс декоратора, две как-то связанными с
ним функциями, скриншот консоли с выполненной программой и
подробные комментарии, которые будут описывать работу вашего
кода

```python
# Декоратор для подсчёта количества вызовов функции
class CallCounter:
    def __init__(self, func):
        self.func = func
        self.call_count = 0  # Счётчик вызовов

    def __call__(self, *args, **kwargs):
        self.call_count += 1  # Увеличиваем счётчик вызовов
        print(f"Функция '{self.func.__name__}' была вызвана {self.call_count} раз(а).")
        return self.func(*args, **kwargs)  # Выполняем оригинальную функцию


# Декорируем две разные функции
@CallCounter
def greet(name):
    """Приветствует пользователя."""
    print(f"Привет, {name}!")

@CallCounter
def add(a, b):
    """Складывает два числа."""
    return a + b


# Тестируем функции
if __name__ == "__main__":
    greet("Вовочка")  # Первый вызов функции greet
    greet("Анна")     # Второй вызов функции greet
    
    result = add(2, 3)  # Первый вызов функции add
    print(f"Результат сложения: {result}")
    
    result = add(10, 20)  # Второй вызов функции add
    print(f"Результат сложения: {result}")

```

### Результат.
![image](https://github.com/user-attachments/assets/69056332-8361-4e97-bb80-d1f58fa2831e)

Выводы:
Созданный декоратор успешно отслеживает количество вызовов функций, выводя информацию о каждом вызове перед выполнением основной логики.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в
двух любых фрагментах кода. Исключения, которые использовались
ранее в работе нельзя воссоздавать. Результатом выполнения задачи
будет: класс исключения, код к котором в двух местах используется это
исключение, скриншот консоли с выполненной программой и
подробные комментарии, которые будут описывать работу вашего
кода

```python
# Создаём собственное исключение
class CustomError(Exception):
    def __init__(self, message):
        self.message = message
        super().__init__(self.message)

# Первая функция: проверка деления на значение, равное 1
def divide_numbers(a, b):
    try:
        if b == 1:
            raise CustomError("Деление на 1 бессмысленно!")  # Вызываем наше исключение
        return a / b
    except CustomError as e:
        print(f"Ошибка: {e}")

# Вторая функция: проверка длины строки
def check_string_length(s):
    try:
        if len(s) < 5:
            raise CustomError("Строка слишком короткая! Минимальная длина: 5 символов.")  # Вызываем исключение
        print(f"Строка '{s}' подходит!")
    except CustomError as e:
        print(f"Ошибка: {e}")

# Тестирование функций
if __name__ == "__main__":
    # Тестируем первую функцию
    print("Результат деления:", divide_numbers(10, 1))  # Здесь будет вызвано исключение
    print("Результат деления:", divide_numbers(10, 2))  # Корректное деление

    # Тестируем вторую функцию
    check_string_length("Hi")  # Здесь будет вызвано исключение
    check_string_length("Hello!")  # Корректная строка

```

### Результат.
![image](https://github.com/user-attachments/assets/350ddce1-a61a-4d45-8efe-e0d452d9a450)

Выводы:
Созданное пользовательское исключение CustomError позволяет эффективно обрабатывать специфические ошибки в различных фрагментах кода. Оно успешно используется для проверки некорректных условий (деление на 1 и короткая строка), обеспечивая понятные сообщения об ошибках. 

## Общие выводы по теме
В ходе выполнения заданий я научился создавать и использовать декораторы, обрабатывать ошибки через try/except, работать с файлами и проверять пользовательский ввод. Эти навыки помогут писать надёжный и удобный для использования код.
